In [1]:
import pandas as pd

In [2]:
# 주택 가격 예측 모델
'''
문6-11> 데이터셋을 불러오고, 아래 항목을 확인하시오.
- 상위 5개 항목 출력
- 데이터의 주요 통계 지표 확인
'''

# 데이터 탐색
df = pd.read_csv('exercise4.csv', index_col=None)
df.head()

   평균 주택 면적  교통 편의지수      교육 점수     인구 밀집도  평균 주택 가격
0    83.910     16.0  67.021277  31.346578      34.8
1    88.920     24.0  55.319149  38.714128      36.6
2    95.925     96.0  80.851064  31.843267      43.4
3   100.170     16.0  36.170213  12.527594      57.2
4    92.430      8.0  22.340426  15.728477      48.2

In [3]:
'''
총 5개의 컬럼을 가지고 있는 데이터로, 마지막 컬럼인 '평균 주택 가격'이 타겟 변수로 사용할 값이다. 나머지 컬럼은 '평균 주택 가격'을 예측하는데 사용할 수 있는 피처로 '평균 주택 면적', '교통 편의 지수', '교육 점수', '인구 밀집도'의 4개의 속성이 존재한다.
'''

"\n총 5개의 컬럼을 가지고 있는 데이터로, 마지막 컬럼인 '평균 주택 가격'이 타겟 변수로 사용할 값이다. 나머지 컬럼은 '평균 주택 가격'을 예측하는데 사용할 수 있는 피처로 '평균 주택 면적', '교통 편의 지수', '교육 점수', '인구 밀집도'의 4개의 속성이 존재한다.\n"

In [6]:
df.describe()

         평균 주택 면적     교통 편의지수       교육 점수      인구 밀집도    평균 주택 가격
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean    94.228740   37.976000   62.238298   30.096302   45.058000
std     10.544196   34.710359   23.038239   19.632020   18.237724
min     53.415000    4.000000    0.000000    0.000000   10.000000
25%     88.245000   16.000000   50.797872   14.514349   34.200000
50%     93.127500   20.000000   68.085106   26.572848   42.400000
75%     99.307500   96.000000   80.851064   41.901214   50.000000
max    131.700000   96.000000  100.000000  100.000000  100.000000

In [5]:
'''
모든 컬럼은 500개의 인스턴스를 포함하고 있다. 평균 주택 면적은 약 53~132의 값이 존재한다. 교통 편의지수, 교육점수, 인구 밀집도는 대략 0에서 100사이의 값으로 분포한다. 평균 주택 가격은 10부터 100사이의 값이 존재한다.
'''

'\n모든 컬럼은 500개의 인스턴스를 포함하고 있다. 평균 주택 면적은 약 53~132의 값이 존재한다. 교통 편의지수, 교육점수, 인구 밀집도는 대략 0에서 100사이의 값으로 분포한다. 평균 주택 가격은 10부터 100사이의 값이 존재한다.\n'