In [15]:
# 데이터 변환
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler

In [16]:
data = {
    '이름': ['오리', '오리', '미금', '기흥', '미금', '기흥', '기흥'],
    '과목': ['수학', '과학', '수학', '과학', '과학', '수학', '수학'],
    '점수': [85, 90, 78, 88, 95, 80, 85]
}

df = pd.DataFrame(data)
df

   이름  과목  점수
0  오리  수학  85
1  오리  과학  90
2  미금  수학  78
3  기흥  과학  88
4  미금  과학  95
5  기흥  수학  80
6  기흥  수학  85

In [17]:
# 1. 데이터 집계(aggregation)
# 특정 열 기준 결합하여 집계 데이터 계산
# 과목별 평균 점수
df.groupby('과목')['점수'].mean()

과목
과학    91.0
수학    82.0
Name: 점수, dtype: float64

In [21]:
# 피벗 테이블 생성
# : pivot(), pivot_table(), crosstab()

# 피벗 테이블로 변환
df.pivot(index='이름', columns='과목', values='점수')

ValueError: Index contains duplicate entries, cannot reshape

In [19]:
# 피벗 테이블 생성 및 평균 계산
df.pivot_table(index='이름', columns='과목', values='점수')

과목    과학    수학
이름
기흥  88.0  82.5
미금  95.0  78.0
오리  90.0  85.0

In [20]:
# 이름과 과목에 따른 점수 합계
pd.crosstab(df['이름'], df['과목'], values=df['점수'], aggfunc='sum')

과목  과학   수학
이름
기흥  88  165
미금  95   78
오리  90   85

In [22]:
# 2. 데이터 인코딩: 레이블 인코딩, one-hot 인코딩
# 예시 데이터
data = ['Red', 'Green', 'Blue', 'Green', 'Red']

# LabelEncoder 객체 생성
encoder = LabelEncoder()

# 'data'를 숫자형으로 변환
encoded_data = encoder.fit_transform(data)
print(encoded_data)

[2 1 0 1 2]

In [23]:
data = {
    'Gender': ['Male', 'Female', 'Female', 'Male'],
    'City': ['Seoul', 'Busan', 'Incheon', 'Seoul']
}

df = pd.DataFrame(data)
df

   Gender     City
0    Male    Seoul
1  Female    Busan
2  Female  Incheon
3    Male    Seoul

In [24]:
# 범주형 변수가 포함된 열에 대해 더미 변수를 생성
pd.get_dummies(df)

   Gender_Female  Gender_Male  City_Busan  City_Incheon  City_Seoul
0          False         True       False         False        True
1           True        False        True         False       False
2           True        False       False          True       False
3          False         True       False         False        True

In [25]:
# 특정 열(Gender)에 대해서만 더미 변수를 생성
pd.get_dummies(df, columns=['Gender'])

      City  Gender_Female  Gender_Male
0    Seoul          False         True
1    Busan           True        False
2  Incheon           True        False
3    Seoul          False         True

In [26]:
# 범주의 카테고리에서 하나의 값을 제외하고 더미 변수를 생성
# 첫 번째 더미 변수 제거(drop_first=True) -> 사전순서대로 제거
pd.get_dummies(df, drop_first=True)

   Gender_Male  City_Incheon  City_Seoul
0         True         False        True
1        False         False       False
2        False          True       False
3         True         False        True

In [27]:
# 3. 스케일 조정
# 샘플 데이터 생성
data = {
    '나이': [25, 30, 45, 50, 60],
    '연봉': [3500, 4000, 5000, 5500, 6500]
}

df = pd.DataFrame(data)
df

   나이    연봉
0  25  3500
1  30  4000
2  45  5000
3  50  5500
4  60  6500

In [ ]:
# Min-Max 정규화
min_max_scaler = MinMaxScaler()
print('Min-Max 정규화된 데이터')
pd.DataFrame(min_max_scaler.fit_transform(df), columns=df.columns)

Min-Max 정규화된 데이터

         나이        연봉
0  0.000000  0.000000
1  0.142857  0.166667
2  0.571429  0.500000
3  0.714286  0.666667
4  1.000000  1.000000

In [29]:
# 표준화 수행
standard_scaler = StandardScaler()
print('표준화된 데이터')
pd.DataFrame(standard_scaler.fit_transform(df), columns=df.columns)

표준화된 데이터

         나이        연봉
0 -1.319456 -1.311220
1 -0.931381 -0.842927
2  0.232845  0.093659
3  0.620920  0.561951
4  1.397071  1.498537

In [30]:
# 사이킷런 패키지는 다양한 데이터셋을 제공한다.
# 붓꽃 데이터셋(iris data)
# - 꽃받침 길이와 너비, 꽃잎 길이와 너비의 4개의 특징 데이터에 따른 품종을 구분한 데이터로 총 150개의 값이 존재한다.

# 데이터 불러오기
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [31]:
df['species'] = iris.target

In [32]:
# 데이터 분포 확인
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [33]:
X = df.drop(columns=['species'])

In [34]:
# 정규화 수행을 위한 객체 생성
minmax_scaler = MinMaxScaler()

# 데이터 변환을 위한 기준값 설정
minmax_scaler.fit(X)

# 정규화 수행
minmax_scaled_data = minmax_scaler.transform(X)

# 정규화 수행 결과를 포함하는 데이터프레임 생성
minmax_scaled_df = pd.DataFrame(data=minmax_scaled_data, columns=iris.feature_names)
minmax_scaled_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,0.428704,0.440556,0.467458,0.458056
std,0.230018,0.181611,0.299203,0.317599
min,0.000000,0.000000,0.000000,0.000000
25%,0.222222,0.333333,0.101695,0.083333
50%,0.416667,0.416667,0.567797,0.500000
75%,0.583333,0.541667,0.694915,0.708333
max,1.000000,1.000000,1.000000,1.000000

In [35]:
# 표준화 수행을 위한 객체 생성
standard_scaler = StandardScaler()

# 데이터 변환을 위한 기준값 설정
standard_scaler.fit(X)

# 표준화 수행
standard_scaled_data = standard_scaler.transform(X)

# 표준화 수행 결과를 포함하는 데이터프레임 생성
standard_scaled_df = pd.DataFrame(data=standard_scaled_data, columns=iris.feature_names)

# 통계 분포 확인
standard_scaled_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,1.500000e+02,1.500000e+02,1.500000e+02,1.500000e+02
mean,-4.736952e-16,-7.815970e-16,-4.263256e-16,-4.736952e-16
std,1.003350e+00,1.003350e+00,1.003350e+00,1.003350e+00
min,-1.870024e+00,-2.433947e+00,-1.567576e+00,-1.447076e+00
25%,-9.006812e-01,-5.923730e-01,-1.226552e+00,-1.183812e+00
50%,-5.250608e-02,-1.319795e-01,3.364776e-01,1.325097e-01
75%,6.745011e-01,5.586108e-01,7.627583e-01,7.906707e-01
max,2.492019e+00,3.090775e+00,1.785832e+00,1.712096e+00